[project]
name = "yt-transcript"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests[socks]>=2.32.3",
    "youtube-transcript-api>=0.6.3",
]
